let materials = [
  {
    id: 0,
    name: "Third Age iron",
    qty: 0,
    goal: 0,
    hide: false,
    level: 5,
    faction: "Agnostic",
    location:
      "Varrock Dig Site\n Kharid-et\n Infernal Source\n Everlight\n Stormguard Citadel\n Warforge",
  },
  {
    id: 1,
    name: "Samite silk",
    qty: 0,
    goal: 0,
    hide: false,
    level: 12,
    faction: "Agnostic",
    location: "Kharid-et",
  },
  {
    id: 2,
    name: "White oak",
    qty: 0,
    goal: 0,
    hide: false,
    level: 17,
    faction: "Agnostic",
    location:
      "Ice Mountain\n Kharid-et\n Infernal Source\n Everlight\n Stormguard Citadel\n Warforge",
  },
  {
    id: 3,
    name: "Goldrune",
    qty: 0,
    goal: 0,
    hide: false,
    level: 20,
    faction: "Agnostic",
    location: "Kharid-et\n Camdozaal",
  },
  {
    id: 4,
    name: "Orthenglass",
    qty: 0,
    goal: 0,
    hide: false,
    level: 20,
    faction: "Agnostic",
    location: "Anachronia",
  },
  {
    id: 5,
    name: "Vellum",
    qty: 0,
    goal: 0,
    hide: false,
    level: 24,
    faction: "Agnostic",
    location: "First Tower",
  },
  {
    id: 6,
    name: "Leather scraps",
    qty: 0,
    goal: 0,
    hide: false,
    level: 29,
    faction: "Agnostic",
    location: "Morytania\n Infernal Source",
  },
  {
    id: 7,
    name: "Soapstone",
    qty: 0,
    goal: 0,
    hide: false,
    level: 60,
    faction: "Agnostic",
    location: "Waiko",
  },
  {
    id: 8,
    name: "Animal furs",
    qty: 0,
    goal: 0,
    hide: false,
    level: 76,
    faction: "Agnostic",
    location: "Feldip",
  },
  {
    id: 9,
    name: "Fossilised bone",
    qty: 0,
    goal: 0,
    hide: false,
    level: 81,
    faction: "Agnostic",
    location: "Ancient Cavern\n Odd Old Man",
  },
  {
    id: 10,
    name: "Stormguard steel",
    qty: 0,
    goal: 0,
    hide: false,
    level: 70,
    faction: "Armadylean",
    location: "Stormguard Citadel\n God Wars Dungeon",
  },
  {
    id: 11,
    name: "Wings of War",
    qty: 0,
    goal: 0,
    hide: false,
    level: 70,
    faction: "Armadylean",
    location: "Stormguard Citadel\n God Wars Dungeon",
  },
  {
    id: 12,
    name: "Armadylean yellow",
    qty: 0,
    goal: 0,
    hide: false,
    level: 76,
    faction: "Armadylean",
    location: "Stormguard Citadel\n Empyrean Citadel",
  },
  {
    id: 13,
    name: "Aetherium alloy",
    qty: 0,
    goal: 0,
    hide: false,
    level: 85,
    faction: "Armadylean",
    location: "Stormguard Citadel\n Empyrean Citadel",
  },
  {
    id: 14,
    name: "Quintessence",
    qty: 0,
    goal: 0,
    hide: false,
    level: 91,
    faction: "Armadylean",
    location: "Stormguard Citadel\n Empyrean Citadel",
  },
  {
    id: 15,
    name: "Malachite green",
    qty: 0,
    goal: 0,
    hide: false,
    level: 76,
    faction: "Bandosian",
    location: "Warforge\n God Wars Dungeon",
  },
  {
    id: 16,
    name: "Mark of the Kyzaj",
    qty: 0,
    goal: 0,
    hide: false,
    level: 76,
    faction: "Bandosian",
    location: "Warforge\n God Wars Dungeon",
  },
  {
    id: 17,
    name: "Vulcanised rubber",
    qty: 0,
    goal: 0,
    hide: false,
    level: 76,
    faction: "Bandosian",
    location: "Warforge\n Feldip",
  },
  {
    id: 18,
    name: "Warforged bronze",
    qty: 0,
    goal: 0,
    hide: false,
    level: 76,
    faction: "Bandosian",
    location: "Warforge\n God Wars Dungeon\n God Wars Dungeon",
  },
  {
    id: 19,
    name: "Yu'biusk clay",
    qty: 0,
    goal: 0,
    hide: false,
    level: 83,
    faction: "Bandosian",
    location: "Warforge\n Feldip",
  },
  {
    id: 20,
    name: "Dragon metal",
    qty: 0,
    goal: 0,
    hide: false,
    level: 73,
    faction: "Dragonkin",
    location: "Orthen\n Daemonheim\n Ancient cavern",
  },
  {
    id: 21,
    name: "Orgone",
    qty: 0,
    goal: 0,
    hide: false,
    level: 73,
    faction: "Dragonkin",
    location: "Orthen\n Daemonheim\n Anachronia",
  },
  {
    id: 22,
    name: "Compass rose",
    qty: 0,
    goal: 0,
    hide: false,
    level: 77,
    faction: "Dragonkin",
    location: "Orthen\n Daemonheim\n Ancient cavern",
  },
  {
    id: 23,
    name: "Carbon black",
    qty: 0,
    goal: 0,
    hide: false,
    level: 78,
    faction: "Dragonkin",
    location: "Orthen\n Daemonheim\n Mount Firewake",
  },
  {
    id: 24,
    name: "Felt",
    qty: 0,
    goal: 0,
    hide: false,
    level: 78,
    faction: "Dragonkin",
    location: "Orthen\n Daemonheim\n Anachronia",
  },
  {
    id: 25,
    name: "Keramos",
    qty: 0,
    goal: 0,
    hide: false,
    level: 42,
    faction: "Saradominist",
    location: "Everlight\n God Wars Dungeon",
  },
  {
    id: 26,
    name: "White marble",
    qty: 0,
    goal: 0,
    hide: false,
    level: 42,
    faction: "Saradominist",
    location: "Everlight\n First Tower",
  },
  {
    id: 27,
    name: "Cobalt blue",
    qty: 0,
    goal: 0,
    hide: false,
    level: 48,
    faction: "Saradominist",
    location: "Everlight\n God Wars Dungeon",
  },
  {
    id: 28,
    name: "Everlight silvthril",
    qty: 0,
    goal: 0,
    hide: false,
    level: 51,
    faction: "Saradominist",
    location: "Everlight\n Barrows mounds",
  },
  {
    id: 29,
    name: "Star of Saradomin",
    qty: 0,
    goal: 0,
    hide: false,
    level: 51,
    faction: "Saradominist",
    location: "Everlight\n Barrows mounds",
  },
  {
    id: 30,
    name: "Cadmium red",
    qty: 0,
    goal: 0,
    hide: false,
    level: 24,
    faction: "Zamorakian",
    location: "Infernal Source\n First Tower",
  },
  {
    id: 31,
    name: "Chaotic brimstone",
    qty: 0,
    goal: 0,
    hide: false,
    level: 29,
    faction: "Zamorakian",
    location: "Infernal Source\n Daemonheim",
  },
  {
    id: 32,
    name: "Demonhide",
    qty: 0,
    goal: 0,
    hide: false,
    level: 29,
    faction: "Zamorakian",
    location: "Infernal Source\n God Wars Dungeon",
  },
  {
    id: 33,
    name: "Eye of Dagon",
    qty: 0,
    goal: 0,
    hide: false,
    level: 36,
    faction: "Zamorakian",
    location: "Infernal Source\n Daemonheim",
  },
  {
    id: 34,
    name: "Hellfire metal",
    qty: 0,
    goal: 0,
    hide: false,
    level: 36,
    faction: "Zamorakian",
    location: "Infernal Source\n God Wars Dungeon",
  },
  {
    id: 35,
    name: "Zarosian insignia",
    qty: 0,
    goal: 0,
    hide: false,
    level: 5,
    faction: "Zarosian",
    location: "Kharid-et\n The Empty Throne Room",
  },
  {
    id: 36,
    name: "Imperial steel",
    qty: 0,
    goal: 0,
    hide: false,
    level: 12,
    faction: "Zarosian",
    location: "Kharid-et\n The Empty Throne Room",
  },
  {
    id: 37,
    name: "Ancient vis",
    qty: 0,
    goal: 0,
    hide: false,
    level: 25,
    faction: "Zarosian",
    location: "Kharid-et\n Slayer Tower",
  },
  {
    id: 38,
    name: "Tyrian purple",
    qty: 0,
    goal: 0,
    hide: false,
    level: 25,
    faction: "Zarosian",
    location: "Kharid-et\n The Empty Throne Room",
  },
  {
    id: 39,
    name: "Blood of Orcus",
    qty: 0,
    goal: 0,
    hide: false,
    level: 58,
    faction: "Zarosian",
    location: "Kharid-et\n Slayer Tower",
  },
];

function checkSaveMats() {
  if (localStorage.getItem("archMats") != null) {
    const saveData = JSON.parse(localStorage.archMats);
    // Add new mats from materials Array above if they don't exist in LocalStorage.
    materials.forEach((mat, i) => {
      if (!saveData[i]) {
        console.debug("Adding new Material: " + mat.name);
        saveData.push(mat);
        return;
      }
      // Update material data, such as location and level.
      saveData.forEach((saveMat) => {
        if (saveMat.name === mat.name) {
          saveMat.id = mat.id;
          saveMat.location = mat.location;
          saveMat.level = mat.level;
        }
      });
    });
    localStorage.archMats = JSON.stringify(saveData);
  } else {
    localStorage.archMats = JSON.stringify(materials);
  }
}

checkSaveMats();
